#!/bin/sh
if [[ $1 == remove ]]; then

rm -rf /var/mobile/Library/Application\ Support/ClassicMusic
declare -a cydia
    cydia=($CYDIA)
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:reload' >&${cydia[0]}"
    else
        echo "Please respring your device."
    fi
fi
