#!/bin/sh

if [[ $1 == install || update ]]; then
cp -f /Applications/AppStore.app/UITabBarFeature*.png /var/mobile/Library/Application\ Support/ClassicMusic/
cp -f /Applications/MobileStore.app/UITabBarMusi*.png /var/mobile/Library/Application\ Support/ClassicMusic/
chown -R mobile:staff /var/mobile/Library/Application\ Support/ClassicMusic
declare -a cydia
    cydia=($CYDIA)
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:reload' >&${cydia[0]}"
    else
        echo "Please respring your device."
    fi
fi
